export const CLIENT_EVENT_TYPES = {
  connectionError: "connectionError",
  connectionStateChanged: "connectionStateChanged",
  conversationAdded: "conversationAdded",
  conversationJoined: "conversationJoined",
  conversationLeft: "conversationLeft",
  conversationRemoved: "conversationRemoved",
  conversationUpdated: "conversationUpdated",
  messageAdded: "messageAdded",
  messageRemoved: "messageRemoved",
  messageUpdated: "messageUpdated",
  participantJoined: "participantJoined",
  participantLeft: "participantLeft",
  participantUpdated: "participantUpdated",
  pushNotification: "pushNotification",
  stateChanged: "stateChanged",
  tokenAboutToExpire: "tokenAboutToExpire",
  tokenExpired: "tokenExpired",
  typingEnded: "typingEnded",
  typingStarted: "typingStarted",
  userSubscribed: "userSubscribed",
  userUnsubscribed: "userUnsubscribed",
  userUpdated: "userUpdated",
};
